services:

  ara-php:
    build:
      dockerfile: php/Dockerfile
    container_name: ara-php-dev
    volumes:
      - ./../BE/:/var/www
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf.d/zzz_memory_limit.ini:/usr/local/etc/php/conf.d/zzz_memory_limit.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ara-net

  ara-nginx:
    image: nginx # :1.25-alpine
    container_name: ara-nginx-dev
    restart: unless-stopped
    ports:
      - "${NGINX_PORTS}"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./../BE/public:/var/www/public
    networks:
      - ara-net

  ara-postgres:
    image: postgres:16-alpine
    container_name: ara-postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORTS}"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - ara-net

networks:
  ara-net:
    driver: bridge
